### Register Admin
POST http://localhost:5184/auth/register/admin
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "AdminPassword123"
}

### Register User
POST http://localhost:5184/auth/register/user
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "UserPassword123"
}

### Login Admin
POST http://localhost:5184/auth/login/admin
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "AdminPassword123"
}

### Login User
POST http://localhost:5184/auth/login/user
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "UserPassword123"
}

### Accessible by User or Admin
GET http://localhost:5184/protected/user-or-admin
Authorization: Bearer <fake-jwt-for-user-or-admin>

### Accessible by Admin Only
GET http://localhost:5184/protected/admin-only
Authorization: Bearer <fake-jwt-for-admin>

### Test prepared statement against sql injection
GET http://localhost:5184/auth/user-by-username?username=exampleUser
Authorization: Bearer <admin-jwt>

### Test get users endpoint
GET http://localhost:5184/auth/users
Authorization: Bearer <admin-jwt>